#!/bin/sh /etc/rc.common
# Copyright (C) 2006-2011 OpenWrt.org

START=95

SERVICE_USE_PID=1
SERVICE_WRITE_PID=1
SERVICE_DAEMONIZE=1

start() {
# 	service_start /usr/bin/ss-redir -c /etc/ss-redir-do.json
service_start /usr/bin/ss-redir -c /etc/ss-redir-gg.json
# 	service_start /usr/bin/ss-tunnel -c /etc/ss-tunnel-do.json -l 7913 -L  8.8.8.8:53 -u
service_start /usr/bin/ss-tunnel -c /etc/ss-tunnel-gg.json -l 7913 -L  8.8.8.8:53 -u
#    service_start /usr/bin/ss-local -c /etc/ss-rescue.json
#    service_start /usr/bin/ss-tunnel -c /etc/ss-tunnel.json -l 7913 -L  123.242.224.50:53 -u
    /usr/bin/shadowsocks-firewall
}

stop() {
    service_stop /usr/bin/ss-redir
    service_stop /usr/bin/ss-tunnel
    service_stop /usr/bin/ss-local
    /etc/init.d/firewall restart
}
